TCP Socket Server listening on host addr 0.0.0.0, port 50050
Registered client FSW_
Registration complete waiting for message.
Registered client GUI_
Registration complete waiting for message.
Ctrl-C received, server shutting down.
socket timed out and shutdown is requested
Quit received!
socket timed out and shutdown is requested
Quit processed!
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 38452)
Traceback (most recent call last):
  File "/usr/lib/python3.10/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/home/jpubuntu/.local/lib/python3.10/site-packages/fprime_gds/executables/tcpserver.py", line 95, in handle
    self.getNewMsg()
  File "/home/jpubuntu/.local/lib/python3.10/site-packages/fprime_gds/executables/tcpserver.py", line 188, in getNewMsg
    SERVER.server_close()
  File "/usr/lib/python3.10/socketserver.py", line 701, in server_close
    self._threads.join()
  File "/usr/lib/python3.10/socketserver.py", line 647, in join
    thread.join()
  File "/usr/lib/python3.10/threading.py", line 1093, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
----------------------------------------
